### ISSUE TITLE
Callback not called

### ISSUE THREAD

**Issue by wackazong** [nioinnovation/python-xbee#28]
Python newbie question: I try to wrap the xBee connection into a class. But the callback gets never called if it is a class method. If it is not in a class it works fine. What can I do?

class Receiver:
	def __enter__(self):
		self.serial_port = serial.Serial('/dev/ttyUSB0', 115200)		
		self.xbee = ZigBee(self.serial_port, escaped=True, callback=self.handlePackets)
		Logger.info('Receiver: enter')
		return self
	def __exit__(self ,type, value, traceback):
		Logger.info('Receiver: exit')
		self.serial_port.close()
	def handlePackets(data):
		Logger.info('Receiver: packet incoming')

**Comment by hansmosh** [comment]
It's hard to say what is wrong since your comment doesn't have any indentation, but try adding `self` to ```def handlePackets(self, data):```.

Questions like this are better asked on a site like stackoverflow.com. GitHub Issues are generally meant for reporting issues with the code in this repository, not with individual issues with using it.
