### ISSUE TITLE
thread problem

### ISSUE THREAD

**Issue by liutairan** [nioinnovation/python-xbee#36]
I am using python-xbee for a little complex case which thread will be used. I am able to request data from API mode coordinator to AT mode router in normal cases, but once I put the code in a thread (actually using "threading") it will never able to read any frame. 

I know this should be something related to thread safety things. Then how to solve this problem?

Thanks~

**Comment by hansmosh** [comment]
This doesn't sound like an issue with the library. You'll find more help from the community by posting your issue to [Stack Overflow](http://stackoverflow.com/) and including the tags `python` and `xbee`. Include example code where you are seeing this issue so we can help trace down the issue.

Go ahead and respond to this comment with a link to your post on Stack Overflow so that anyone who comes across this can find your question (and hopefully an answer) there.

**Comment by liutairan** [comment]
No, it is not. I think it should come from the thread related things because this library uses thread. I will check online how to fix this. Thanks anyway.
